"""adds user table

Revision ID: 1df6ac8321e9
Revises: 05e20be7cbd7
Create Date: 2022-12-05 22:50:31.308702

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1df6ac8321e9"
down_revision = "05e20be7cbd7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
