"""adds user table

Revision ID: b1f0f481b98f
Revises: ec026d75f9f0
Create Date: 2022-12-06 00:27:24.883196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f0f481b98f'
down_revision = 'ec026d75f9f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('description', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('customer', sa.String(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['customer'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'customer')
    op.drop_column('orders', 'description')
    # ### end Alembic commands ###
