"""adds user table

Revision ID: ec026d75f9f0
Revises: 1df6ac8321e9
Create Date: 2022-12-05 23:21:33.015752

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ec026d75f9f0"
down_revision = "1df6ac8321e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("surname", sa.String(), nullable=True))
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("full_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("users", "surname")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
